;;; .emacs --- Luke Lawlor's GNU Emacs configuration all in 1 file
;;; init.el --- Luke Lawlor's GNU Emacs configuration
;; This file is hosted at <https://codeberg.org/lukelawlor/dotfiles>
;; as part of my dotfiles.
;;
;; Also in my dotfiles is the file '.emacs' in the root directory. The
;; purpose of that file is to contain all elisp files in this
;; directory, '.config/emacs', for easy deployment on systems. My
;; '.emacs' is generated by concatenating all files in this directory
;; & removing elisp calls to 'load-file'.
;;
;; Search for the string "placeholder" to find areas where you're
;; meant to insert your custom values.
;;
;; Last modified: 2026.02.04
					; variables
(setq-default
 auto-save-default nil
 default-input-method "russian-computer"
 display-fill-column-indicator-character ?.
 display-time-24hr-format t
 frame-title-format "emacs %b"
 icon-title-format "emacsóg"
 indent-tabs-mode nil
 initial-buffer-choice "~/i"
 initial-scratch-message ""
 outline-default-state 'outline-show-only-headings
 ;; mail (see function 'my-mail' for other mail configurations)
 user-mail-address "placeholder@gmail.com"
 ;; rmail (for reading local mail on a GNU/Linux system)
 rmail-file-name "~/rmail/rmail"
 rmail-preserve-inbox nil
 rmail-primary-inbox-list (list (concat "/var/mail/"
                                        (user-login-name)))
 ;; security
 safe-local-variable-values '((eval toggle-truncate-lines 1))
 ;; my variables
 my-home-directory "~/"
 my-init-file "~/.config/emacs/init.el"
 ;;; my done text, see function 'my-done'
 my-dt "хорошо"
 )
(set-terminal-coding-system 'utf-8)
(put 'downcase-region 'disabled nil)
(put 'list-timers 'disabled nil)
(put 'narrow-to-region 'disabled nil)
(put 'upcase-region 'disabled nil)
(put 'scroll-left 'disabled nil)
					; modes
(display-time-mode 1)
(global-display-fill-column-indicator-mode 1)
;;(repeat-mode 1)
					; functions
(defun my-font-size (height)
  "Set the default font size by calling function
'set-face-attribute'. For more information, visit Info node
'(elisp)Attribute Functions'."
  (set-face-attribute 'default nil :height height))
(defun my-scratch nil
  "Switch to the *scratch* buffer"
  (interactive)
  (switch-to-buffer "*scratch*" ))
(defun my-done nil
  "For to-do lists, insert text to symbolize a completed task"
  (interactive)
  (move-beginning-of-line nil)
  (insert (concat "(" my-dt ") "))
  (move-beginning-of-line nil))
(defun ding-much (number seconds)
  "Call 'ding' NUMBER times with SECONDS seconds between each ding"
  (ding)
  (setq ding-timer (run-at-time seconds seconds 'ding)
	ding-timer-stop (run-at-time
			 (* seconds (- number 1))
			 nil
			 'cancel-timer ding-timer)))
(defun ding-stop nil
  "Stop the dinging started by function 'ding-much'"
  (interactive)
  (cancel-timer ding-timer)
  (cancel-timer ding-timer-stop))
(defun my-msg (msg)
  "Display the message MSG to the user in a way that should catch
their attention"
  (ding-much 40 0.15)
  (message "Sending the following attention-catching message: %s" msg)
  (read-from-minibuffer (concat msg "! (press enter to continue) "))
  (ding-stop))
(defun my-timer nil
  "Create a simple timer to ding later"
  (interactive)
  (setq my-timer-purpose (read-string "To do: ")
	my-timer-seconds (* 60 (read-number "Minutes until ding: "))
	my-timer-object (run-at-time
			 my-timer-seconds
			 nil
			 'my-msg
			 (concat
                          "Timer for "
                          my-timer-purpose
                          " is over"))
        my-timer-start (time-convert (current-time) 'integer))
  (message "You have %d minutes to %s"
	   (/ my-timer-seconds 60)
	   my-timer-purpose))
(defun my-timer-info nil
  "Output info about the current timer created with 'my-timer'"
  (interactive)
  (unless my-timer-object (error "No timer exists"))
  (setq my-time-left-sec (- my-timer-seconds (-
                                              (time-convert
                                               (current-time)
                                               'integer)
                                              my-timer-start))
        my-time-left-min (/ my-time-left-sec 60))
  (message "The time left to %s is %d minutes, or %d seconds"
           my-timer-purpose
           my-time-left-min
           my-time-left-sec))
(defun my-timer-stop nil
  "Cancel the latest timer created with 'my-timer'"
  (interactive)
  (unless my-timer-object (error "No timer exists"))
  (cancel-timer my-timer-object)
  (setq my-timer-object nil)
  (message "The time to %s has been canceled" my-timer-purpose))
(defun my-find-zi (arg)
  "Find 1 or more Chinese characters (han zi) in a dictionary,
specifically CC-CEDICT
<https://www.mdbg.net/chinese/dictionary?page=cc-cedict>.  With a
prefix argument, search for simplified characters; else, search
for traditional characters. The characters to search for are
assumed to be stored as the most recent kill in the kill ring."
  (interactive "P")
  (beginning-of-buffer)
  (setq my-zi (current-kill 0 t)) ;; zi to search for
  (condition-case nil
      (if arg
          (search-forward-regexp
           (concat "^" (make-string (length my-zi) ?.) " " my-zi))
        (search-forward-regexp (concat "^" my-zi " ")))
    (error nil))
  (recenter-top-bottom 0))
(defun my-find-zi-from-text (arg)
  "Run 'my-find-zi' on the character(s) from point to point + the
magnitude of ARG. If ARG is positive, then traditional
character(s) are sought; else, simplified character(s) are
sought. This assumes that only 2 windows are open: one with
Chinese text (the current window) & one with the Chinese
dictionary."
  (interactive "p")
  (setq my-find-zi-arg nil)
  (if (< arg 0) (progn (setq arg (- arg) my-find-zi-arg t)))
  (kill-ring-save (point) (+ arg (point)))
  (other-window 1)
  (my-find-zi my-find-zi-arg)
  (other-window 1))
(defun my-find-zi-from-dict (arg)
  "Run 'my-find-zi' on the character(s) from point to point + the
magnitude of ARG. If ARG is positive, then traditional
character(s) are sought; else, simplified character(s) are
sought. This function assumes that the current buffer is the
Chinese dictionary. This function is the same as
'my-find-zi-from-text' but without the 2 calls to
'other-window'."
  (interactive "p")
  (setq my-find-zi-arg nil)
  (if (< arg 0) (progn (setq arg (- arg) my-find-zi-arg t)))
  (kill-ring-save (point) (+ arg (point)))
  (my-find-zi my-find-zi-arg))
(defun my-mail nil
  "Set variables for using mail. Some variables are expected to be
set before calling this function. Here they are:
user-mail-address. You can call 'my-mail-prompt' to be prompted
for values of these variables; they will be set & then 'my-mail'
will be called.

This function is currently configured for gmail by default."
  (interactive)
  (setq
   user-full-name ""
   mail-host-address "gmail.com"
   ;; smtp
   send-mail-function 'smtpmail-send-it
   smtpmail-smtp-user user-mail-address
   smtpmail-smtp-server "smtp.gmail.com"
   smtpmail-smtp-service 587 ;; port
   smtpmail-servers-requiring-authorization "smtp.gmail.com"
   ;; gnus
   ;;; nnimap
   gnus-select-method '(nnimap "imap.gmail.com")
   nnimap-user user-mail-address
   ;;; avoid writing to disk
   gnus-use-dribble-file nil
   gnus-save-newsrc-file nil
   ;;;; this does not prevent writing to disk; it prevents reading
   gnus-read-newsrc-file nil
   ;;;; I cannot stop the '.newsrc.eld' file from being saved when
   ;;;; exiting gnus. For now, I will just move its location. It is
   ;;;; now 'bad.eld'.
   gnus-startup-file (concat my-home-directory "bad")
   ))
(defun my-mail-prompt nil
  "Prompt for 'user-mail-address'; then run 'my-mail'"
  (interactive)
  (setq user-mail-address (read-string "Mail address: "))
  ;; convert abbreviated addresses into full addresses
  (if (string-equal user-mail-address "placeholder")
      (setq my-mail-addr "placeholder@gmail.com"))
  ;; set the remaining mail variables
  (my-mail))
(defun my-mail-switch nil
  "Switch mail accounts in gnus"
  (interactive)
  (switch-to-buffer "*scratch*")
  (end-of-buffer)
  (insert "
(setq gnus-select-method
 '(nnimap \"imap.gmail.com\" (nnimap-user \"\")))")
  (search-backward "\"")
  (my-mail-prompt)
  (insert user-mail-address)
  (beginning-of-line)
  (previous-line)
  (set-mark (point))
  (next-line)
  (end-of-line)
  (eval-region (mark) (point)))
(defun tetris nil
  "Экономь время"
  (interactive)
  (message "Нет тетриса для тебя!"))
                                        ; functions from other files
;;(load-file "~/.config/emacs/pomo.el")
					; aliases
(defalias 'd 'desktop-read)
(defalias 'dc 'describe-char)
(defalias 'ds 'desktop-save)
(defalias 'e 'eww-open-file)
(defalias 'yes-or-no-p 'y-or-n-p)
;; my functions
(defalias 'md 'my-done)
(defalias 'mf 'my-font-size)
(defalias 's 'my-scratch)
;;; pomo
(defalias 'pm 'pomo)
(defalias 'pm-d 'pomo-start-default)
(defalias 'pm-n 'pomo-skip) ;; n for next pomodoro timer section
(defalias 'pm-s 'pomo-stop)
(defalias 'pm-i 'pomo-info)
(defalias 'p 'pomo-start-default)
;; modes
(defalias 'f 'auto-fill-mode)
(defalias 'g 'gnus)
(defalias 'i 'paragraph-indent-minor-mode)
(defalias 'o 'outline-mode)
(defalias 'r 'repeat-mode)
(defalias 'v 'view-mode)
(defalias 'w 'display-fill-column-indicator-mode) ;; w for page width
					; keys
;; custom prefix commands
(define-prefix-command 'my-ext-map)
(global-set-key (kbd "M-o") 'my-ext-map)
;; basic functions
(global-set-key (kbd "M-/") 'my-done)
;; timer
(global-set-key (kbd "M-o t") 'my-timer)
(global-set-key (kbd "M-o i") 'my-timer-info)
(global-set-key (kbd "M-o m") 'my-timer-stop)
;; chinese dictionary search
(global-set-key (kbd "M-o f") 'my-find-zi-from-text)
(global-set-key (kbd "M-o d") 'my-find-zi-from-dict)
(global-set-key (kbd "M-o s") 'my-find-zi)
;; pomo
(global-set-key (kbd "M-o p") 'pomo)
(global-set-key (kbd "M-o b") 'pomo-start-default)
(global-set-key (kbd "M-i") 'pomo-info)
(global-set-key (kbd "M-o x") 'pomo-stop)
(global-set-key (kbd "M-o n") 'pomo-skip) ;; n for next pomodoro timer
                                          ;; section
;; input methods
(global-set-key (kbd "M-n") #'(lambda nil (interactive)
                                (set-input-method
                                 "japanese-hankaku-kana")))
(global-set-key (kbd "M-N") #'(lambda nil (interactive)
                                (set-input-method "japanese")))
(global-set-key (kbd "M-]") #'(lambda nil (interactive)
                                (set-input-method
                                 "chinese-py-punct-b5")))
(global-set-key (kbd "M-.") #'(lambda nil (interactive)
                                (set-input-method
                                 "russian-computer")))
(global-set-key (kbd "M-O") #'(lambda nil (interactive)
                                (set-input-method "greek-postfix")))
(global-set-key (kbd "M-o v") #'(lambda nil (interactive)
                                  (set-input-method
                                   "vietnamese-telex")))
(global-set-key (kbd "M-o h") #'(lambda nil (interactive)
                                  (set-input-method "korean-hangul")))
(global-set-key (kbd "M-o j") #'(lambda nil (interactive)
                                  (set-input-method
                                   "japanese-hankaku-kana")))
(global-set-key (kbd "M-o z") #'(lambda nil (interactive)
                                  (set-input-method
                                   "chinese-py-punct")))
(global-set-key (kbd "M-o e") #'(lambda nil (interactive)
                                  (set-input-method
                                   "spanish-postfix")))
(global-set-key (kbd "M-o g") #'(lambda nil (interactive)
                                  (set-input-method
                                   "german-postfix")))
(global-set-key (kbd "M-o l") #'(lambda nil (interactive)
                                  (set-input-method
                                   "icelandic-keyboard")))
                                        ; function calls
;; show the clock at the start of the mode line
;;(setq mode-line-front-space mode-line-misc-info)
(my-mail)
(if (window-system)
    (progn
      ;; modes
      (global-hl-line-mode 1)
      (menu-bar-mode -1)
      (scroll-bar-mode -1)
      (tool-bar-mode -1)
      ;; default font size
      ;;(my-font-size 120) ;; small
      ;;(my-font-size 380) ;; large
      (my-font-size 120))
  (progn
    ;; can load a terminal theme
    ))
;;; init.el ends here
;;; pomo.el --- pomodoro timer
;; This is part of Luke Lawlor's GNU Emacs configuration, hosted at
;; <https://codeberg.org/lukelawlor/dotfiles>.
(defun pomo-start (work break lbreak)
  "Run a pomodoro timer with WORK seconds for work time, BREAK
seconds for break time & LBREAK seconds for long break time"
  (message "Starting pomodoro timer (%d %d %d)" work break lbreak)
  (setq
   pomo-seconds-work work
   pomo-seconds-break break
   pomo-seconds-lbreak lbreak)
  (pomo-section 0))
(defun pomo nil
  "Run 'pomo-start' but prompt for the values of the arguments
 interactively"
  (interactive)
  (pomo-start
   (* 60 (read-number "Minutes of work: "))
   (* 60 (read-number "Minutes of break: "))
   (* 60 (read-number "Minutes of long break: "))))
(defun pomo-section-end (iteration)
  "This function is to be called at the end of a pomodoro timer
section which is invoked by calling 'pomo-section'"
  (my-msg (concat "Section " pomo-name " is no more"))
  (pomo-section (+ 1 iteration)))
(defun pomo-section (iteration)
  "Execute a pomodoro timer section using number ITERATION to tell
whether it is work time, break time, or something else. ITERATION
must be in the range [0, 5]. The following text maps each
iteration value to a time:
0 = work #1
1 = break #1
2 = work #2
3 = break #2
4 = work #3
5 = long break"
  (if (> iteration 5) (setq iteration 0))
  (setq pomo-iteration iteration)
  ;; using ITERATION, pick the values for 'pomo-name' & 'pomo-seconds'
  ;; TODO: find out which syntax makes this better
  (if (= iteration 0) (setq pomo-name "work"
                            pomo-seconds pomo-seconds-work))
  (if (= iteration 1) (setq pomo-name "break"
                            pomo-seconds pomo-seconds-break))
  (if (= iteration 2) (setq pomo-name "work"
                            pomo-seconds pomo-seconds-work))
  (if (= iteration 3) (setq pomo-name "break"
                            pomo-seconds pomo-seconds-break))
  (if (= iteration 4) (setq pomo-name "work"
                            pomo-seconds pomo-seconds-work))
  (if (= iteration 5) (setq pomo-name "lbreak"
                            pomo-seconds pomo-seconds-lbreak))
  ;; cancel a previous timer if it exists
  (if pomo-timer-running (cancel-timer pomo-timer))
  ;; start the new timer
  (setq
   pomo-timer (run-at-time pomo-seconds nil 'pomo-section-end
                           iteration)
   pomo-timer-running t
   pomo-timer-start (time-convert (current-time) 'integer))
  (message "Pomo section %s lasts %d minutes, or %d seconds"
	   pomo-name
	   (/ pomo-seconds 60)
	   pomo-seconds))
(defun pomo-skip nil
  "Skip the current pomodoro timer section"
  (interactive)
  (if (not pomo-timer-running)
      (message "No pomo timer is running")
    (cancel-timer pomo-timer)
    (pomo-section (+ 1 pomo-iteration))))
(defun pomo-stop nil
  "Stop any existing pomodoro timer"
  (interactive)
  (if (not pomo-timer-running)
      (message "No pomo timer is running")
    (cancel-timer pomo-timer)
    (setq pomo-timer-running nil)
    (message "Stopped pomo timer")))
(defun pomo-info nil
  "Output info about the current pomo timer"
  (interactive)
  (if (not pomo-timer-running)
    (message "No pomo timer is running")
    (setq pomo-seconds-left (- pomo-seconds
			       (-
                                (time-convert (current-time) 'integer)
                                pomo-timer-start))
	  pomo-minutes-left (/ pomo-seconds-left 60))
    (message "Pomo section %s lasts %d minutes, or %d seconds"
	     pomo-name
	     pomo-minutes-left
	     pomo-seconds-left)))
(defun pomo-start-default nil
  "Run 'pomo-start' with default arguments"
  (interactive)
  (pomo-start (* 60 25) (* 60 5) (* 60 5)))
;;; pomo.el ends here
;;; .emacs ends here
