(require 'autothemer)

(autothemer-deftheme cakgruv "Cak Gruvbox"
		     ;; Specify the color classes used by the theme
		     ((((class color) (min-colors #xFFFFFF)))

		      ;; Specify the color palette, color columsn correspond to each of the classes above

		      ;; cakgruv
		      (cakgruv-red     "#fb4934")
		      (cakgruv-green   "#98971a")
		      (cakgruv-blue    "#458588")
		      (cakgruv-magenta "#b16286")
		      (cakgruv-yellow  "#d79921")
		      (cakgruv-orange  "#d79921")
		      (cakgruv-cyan    "#689d6a")
		      (cakgruv-gray    "#928374")
		      (cakgruv-fvwm-fg "#458588")
		      (cakgruv-fvwm-bg "#000000")
		      (cakgruv-fvwm-hi "#000000")
		      (cakgruv-fvwm-sh "#000000")
		      (cakgruv-fg      "#ebdbb2")
		      (cakgruv-bg      "#282828")
		      (cakgruv-bg0     "#3c3836")
		      (cakgruv-bg1     "#504945")
		      (cakgruv-bg2     "#665c54")
                      )

		      ;; Specifications for Emacs faces.
		      ;; Simpler than deftheme, just specify a face name and
		      ;; a plist of face definitions (nested for :underline, :box etc.)
		     ((default (:foreground cakgruv-fg :background cakgruv-bg))
		      (bold (:weight 'bold))
		      (italic (:slant 'italic))
		      (bold-italic (:weight 'bold :slant 'italic))
		      (underline (:underline t))
		      (shadow (:foreground cakgruv-gray))
		      (button (:underline t :foreground cakgruv-blue))
		      (error (:foreground cakgruv-red))
		      (warning (:foreground cakgruv-yellow))
		      (success (:foreground cakgruv-green))
		      (show-paren-match (:background cakgruv-cyan))
		      (show-paren-mismatch (:foreground cakgruv-bg :background cakgruv-fg))
		      (link (:underline t :foreground cakgruv-blue))
		      (link-visited (:foreground cakgruv-magenta :inherit 'link))
		      (highlight (:background cakgruv-bg0))
		      (region (:extend t :background cakgruv-blue :foreground cakgruv-bg))
		      (mode-line
			(:foreground cakgruv-yellow :background cakgruv-bg0 :weight 'normal :inverse-video nil))
		      (mode-line-inactive
			(:foreground cakgruv-blue :background cakgruv-bg0 :weight 'normal))
		      (window-divider (:foreground cakgruv-fvwm-bg))
		      (window-divider-first-pixel (:foreground cakgruv-fvwm-hi))
		      (window-divider-last-pixel (:foreground cakgruv-fvwm-sh))
		      (minibuffer-prompt (:foreground cakgruv-blue))
		      (fringe (:background cakgruv-bg0))
		      (mouse-drag-and-drop-region (:inherit 'region))
		      (isearch (:foreground cakgruv-bg :background cakgruv-fg))
		      (isearch-fail (:foreground cakgruv-bg :background cakgruv-red))
		      (lazy-highlight (:inherit 'highlight))
		      (isearch-group-1 (:foreground cakgruv-bg :foreground cakgruv-fg))
		      (isearch-group-2 (:foreground cakgruv-bg :foreground cakgruv-fg))
		      (file-name-shadow (:inherit 'shadow))
		      (query-replace (:inherit 'isearch))
		      (buffer-menu-buffer (:weight 'normal))
		      (hl-line (:extend t :inherit 'highlight))
		      (header-line (:foreground cakgruv-fg :background cakgruv-bg0))
		      (widget-documentation (:foreground cakgruv-green))
		      (widget-button (:weight 'bold))
		      (widget-field (:extend t :background cakgruv-bg0))
		      (widget-single-line-field (:background cakgruv-bg0))
		      (widget-inactive (:inherit 'shadow))
		      (widget-button-pressed (:foreground cakgruv-red))
		      (custom-invalid (:foreground cakgruv-bg :background cakgruv-red))
		      (custom-rogue (:foreground cakgruv-bg :background cakgruv-fg))
		      (custom-modified (:foreground cakgruv-bg :background cakgruv-fg))
		      (custom-set (:foreground cakgruv-fg :background cakgruv-bg0))
		      (custom-changed (:foreground cakgruv-bg :background cakgruv-fg))
		      (custom-themed (:foreground cakgruv-bg :background cakgruv-fg))
		      (custom-saved (:underline t))
		      (custom-button
		       (:box
			(:line-width 2 :style 'released-button)
			:inherit 'button))
		      (custom-button-mouse (:inherit 'custom-button))
		      (custom-button-unraised (:inherit 'underline))
		      (custom-button-pressed
		       (:box
			(:line-width 2 :style 'pressed-button)
			:foreground cakgruv-fvwm-fg :background-cakgruv-fvwm-bg))
		      (custom-button-pressed-unraised (:foreground cakgruv-fg :inherit 'custom-button-unraised))
		      (custom-state (:foreground cakgruv-green))
		      (custom-link (:inherit 'link))
		      (custom-comment (:inherit 'font-lock-comment-face))
		      (custom-comment-tag (:inherit 'font-lock-comment-face))
		      (custom-variable-obsolete (:inherit 'custom-invalid))
		      (custom-variable-tag (:weight 'bold))
		      (custom-variable-button (:weight 'bold :underline t))
		      (custom-visibility (:height 0.8 :inherit 'link))
		      (custom-face-tag (:inherit 'custom-variable-tag))
		      (custom-group-tag-1 (:height 1.2 :weight 'bold :foreground cakgruv-red :inherit 'variable-pitch))
		      (custom-group-tag (:height 1.2 :weight 'bold :foreground cakgruv-fg :inherit 'variable-pitch))
		      (custom-group-subtitled (:weight 'bold))
		      (calendar-today (:underline t))
		      (diary (:foreground cakgruv-red))
		      (holiday (:background cakgruv-fvwm-hi))
		      (calendar-weekday-header (:inherit 'font-lock-constant-face))
		      (calendar-weekend-header (:inherit 'font-lock-comment-face))
		      (calendar-month-header (:inherit 'font-lock-function-name-face))
		      (outline-1 (:foreground cakgruv-blue))
		      (outline-2 (:foreground cakgruv-green))
		      (outline-3 (:foreground cakgruv-yellow))
		      (outline-4 (:foreground cakgruv-magenta))
		      (outline-5 (:foreground cakgruv-red))
		      (outline-6 (:foreground cakgruv-cyan))
		      (outline-7 (:foreground cakgruv-green))
		      (outline-8 (:foreground cakgruv-yellow))
		      (help-key-binding (:foreground cakgruv-fvwm-fg :background cakgruv-fvwm-bg))
		      (secondary-selection (:background cakgruv-bg0))
		      
		      ;; font lock
		      (font-lock-comment-face              (:foreground cakgruv-blue))
		      (font-lock-comment-delimiter-face    (:inherit 'font-lock-comment-face))
		      (font-lock-constant-face             (:foreground cakgruv-green))
		      (font-lock-string-face               (:foreground cakgruv-red))
		      (font-lock-doc-face                  (:inherit 'font-lock-string-face))
		      (font-lock-doc-markup-face           (:inherit 'font-lock-constant-face))
		      (font-lock-keyword-face              (:foreground cakgruv-yellow))
		      (font-lock-builtin-face              (:foreground cakgruv-yellow))
		      (font-lock-function-name-face        (:foreground cakgruv-fg))
		      (font-lock-variable-name-face        (:foreground cakgruv-fg))
		      (font-lock-type-face                 (:foreground cakgruv-green))
		      (font-lock-constant-face             (:foreground cakgruv-cyan))
		      (font-lock-warning-face              (:inherit 'error))
		      (font-lock-preprocessor-face         (:foreground cakgruv-magenta))
		      (font-lock-regexp-grouping-backslash (:inherit 'bold))
		      (font-lock-regexp-grouping-construct (:inherit 'bold))
		      
		      ;; info
		      (info-node (:weight 'bold :slant 'italic :foreground cakgruv-red))
		      (info-menu-star (:foreground cakgruv-red))
		      (info-xref (:inherit 'link))
		      (info-xref-visited (:inherit ('link-visited 'info-xref)))

		      ;; ansi colors
		      (ansi-color-black (:foreground cakgruv-fvwm-fg :background cakgruv-fvwm-fg))
		      (ansi-color-red (:foreground cakgruv-red :background cakgruv-red))
		      (ansi-color-green (:foreground cakgruv-green :background cakgruv-green))
		      (ansi-color-yellow (:foreground cakgruv-yellow :background cakgruv-yellow))
		      (ansi-color-blue (:foreground cakgruv-blue :background cakgruv-blue))
		      (ansi-color-magenta (:foreground cakgruv-magenta :background cakgruv-magenta))
		      (ansi-color-cyan (:foreground cakgruv-cyan :background cakgruv-cyan))
		      (ansi-color-white (:foreground cakgruv-bg :background cakgruv-bg))
		      (ansi-color-bright-black (:inherit 'ansi-color-black))
		      (ansi-color-bright-red (:inherit 'ansi-color-red))
		      (ansi-color-bright-green (:inherit 'ansi-color-green))
		      (ansi-color-bright-yellow (:inherit 'ansi-color-yellow))
		      (ansi-color-bright-blue (:inherit 'ansi-color-blue))
		      (ansi-color-bright-magenta (:inherit 'ansi-color-magenta))
		      (ansi-color-bright-cyan (:inherit 'ansi-color-cyan))
		      (ansi-color-bright-white (:inherit 'ansi-color-white))

		      ;; flyspell
		      (flyspell-incorrect
		       (:underline
			(:style 'wave :color cakgruv-red)))
		      (flyspell-duplicate
		       (:underline
			(:style 'wave :color cakgruv-yellow)))

		      ;; ido
		      (ido-first-match (:weight 'bold))
		      (ido-only-match (:foreground cakgruv-green))
		      (ido-subdir (:foreground cakgruv-red))
		      (ido-virtual (:inherit 'font-lock-builtin-face))
		      (ido-indicator (:width 'condensed :foreground cakgruv-bg :background cakgruv-red))
		      (ido-incomplete-regexp (:inherit 'font-lock-warning-face))

		      ;; org
		      (org-default (:inherit 'default))
		      (org-hide (:foreground cakgruv-gray))
		      (org-dispatcher-highlight (:weight 'bold :inherit 'highlight))
		      ;;(org-level-1 (:inherit 'outline-1 :height 1.25))
		      ;;(org-level-2 (:inherit 'outline-2 :height 1.1))
		      (org-level-1 (:inherit 'outline-1))
		      (org-level-2 (:inherit 'outline-2))
		      (org-level-3 (:inherit 'outline-3))
		      (org-level-4 (:inherit 'outline-4))
		      (org-level-5 (:inherit 'outline-5))
		      (org-level-6 (:inherit 'outline-6))
		      (org-level-7 (:inherit 'outline-7))
		      (org-level-8 (:inherit 'outline-8))
		      (org-special-keyword (:inherit 'font-lock-keyword-face))
		      (org-column (:weight 'normal :slant 'normal :underline nil :strike-through nil :background cakgruv-bg0))
		      (org-column-title (:weight 'bold :underline t :background cakgruv-bg0))
		      (org-footnote (:underline t :foreground cakgruv-yellow))
		      (org-ellipsis (:underline t :foreground cakgruv-yellow))
		      (org-target (:underline t))
		      (org-date (:foreground cakgruv-magenta))
		      (org-date-selected (:inverse-video t :foreground cakgruv-red))
		      (org-sexp-date (:foreground cakgruv-red))
		      (org-todo (:weight 'bold :foreground cakgruv-red))
		      (org-done (:weight 'bold :foreground cakgruv-green))
		      (org-agenda-done (:foreground cakgruv-green))
		      (org-headline-todo (:foreground cakgruv-red))
		      (org-headline-done (:foreground cakgruv-green))
		      (org-priority (:inherit 'font-lock-keyword-face))
		      (org-checkbox (:inherit 'bold :foreground cakgruv-blue))
		      (org-checkbox-statistics-todo (:inherit 'org-todo :foreground cakgruv-green))
		      (org-checkbox-statistics-done (:inherit 'org-done :foreground cakgruv-green))
		      (org-table (:foreground cakgruv-blue))
		      (org-table-header (:foreground cakgruv-fg :background cakgruv-bg0 :inherit 'org-table))
		      (org-formula (:foreground cakgruv-magenta))
		      (org-code (:inherit 'shadow))
		      (org-meta-line (:inherit 'font-lock-comment-face))
		      (org-document-title (:weight 'normal :foreground cakgruv-magenta))
		      (org-document-info (:foreground cakgruv-fg))
		      (org-document-info-keyword (:inherit 'shadow))
		      (org-block (:extend t :inherit 'shadow))
		      (org-block-begin-line (:extend t :inherit 'org-meta-line))
		      (org-block-end-line (:extend t :inherit 'org-block-begin-line))
		      (org-clock-overlay (:foreground cakgruv-magenta :background cakgruv-bg0))
		      (org-agenda-structure (:foreground cakgruv-green))
		      (org-agenda-structure-secondary (:inherit 'org-agenda-structure))
		      (org-agenda-structure-filter (:inherit ('org-warning 'org-agenda-structure)))
		      (org-agenda-date (:inherit 'org-agenda-structure))
		      (org-agenda-date-today (:weight 'bold :slant 'italic :inherit 'org-agenda-date))
		      (org-agenda-date-weekend-today (:inherit 'org-agenda-date-today))
		      (org-agenda-clocking (:inherit 'secondary-selection))
		      (org-agenda-date-weekend (:weight 'bold :inherit 'org-agenda-date))
		      (org-scheduled (:foreground cakgruv-green))
		      (org-scheduled-today (:foreground cakgruv-green))
		      (org-agenda-dimmed-todo-face (:foreground cakgruv-gray))
		      (org-scheduled-previously (:foreground cakgruv-red))
		      (org-imminent-deadline (:inherit 'org-warning))
		      (org-upcoming-deadline (:foreground cakgruv-red))
		      (org-upcoming-distant-deadline (:inherit 'org-default))
		      (org-agenda-restriction-lock (:background cakgruv-bg0))
		      (org-agenda-filter-tags (:inherit 'mode-line))
		      (org-agenda-filter-category (:inherit 'mode-line))
		      (org-agenda-filter-effort (:inherit 'mode-line))
		      (org-agenda-filter-regexp (:inherit 'mode-line))
		      (org-time-grid (:foreground cakgruv-yellow))
		      (org-latex-and-related (:foreground cakgruv-magenta))
		      (org-mode-line-clock-overrun (:background cakgruv-red :inherit 'mode-line))

		      ;; dired
		      (dired-broken-symlink (:weight 'bold :foreground cakgruv-bg :background cakgruv-red))

		      ;; avy
		      (avy-lead-face (:foreground cakgruv-bg :background cakgruv-red))
		      (avy-lead-face-0 (:foreground cakgruv-bg :background cakgruv-blue))
		      (avy-lead-face-1 (:foreground cakgruv-bg :background cakgruv-gray))
		      (avy-lead-face-2 (:foreground cakgruv-bg :background cakgruv-magenta))
		      )

                     ;; set the fringe size to 9 pixels
		     ;; this is the border size for my terminals
                     (fringe-mode 9)

		     ;; set the cursor color and have it work in new frames using emacsclient
		     ;; light
		     (setq default-frame-alist '((cursor-color . "#ebdbb2")))
		     ;; dark
		     ;;(setq default-frame-alist '((cursor-color . "#AEB2C3")))
		     )

(provide-theme 'cakgruv)
